In [4]:
import numpy as np
import nnfs
import matplotlib.pyplot as plt
from nnfs.datasets import spiral_data

nnfs.init()


class Layer_Dense:

    # Initialize Weights and Biases
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [5]:
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2, 3)
dense1.forward(X)
print(dense1.output[:5])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


In [8]:
## Activation Functions ##

# Simple ReLU (No Library) 
inputs = [0, 2, -1, 3.3, -2.7,  1.1, 2.2, -100]
output = list(range(len(inputs)))

for index, input in enumerate(inputs):
    output[index] = max(0, input)

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [9]:
# Using Numpy
inputs = [0, 2, -1, 3.3, -2.7,  1.1, 2.2, -100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [19]:
# ReLU Class
class Activation_ReLU:

    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense1.forward(X)
activation1.forward(dense1.output)

print(activation1.output[:5])


[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [4.0287432e-05 0.0000000e+00 0.0000000e+00]
 [9.1045447e-05 0.0000000e+00 0.0000000e+00]
 [1.1607886e-04 0.0000000e+00 0.0000000e+00]
 [1.8409541e-04 0.0000000e+00 0.0000000e+00]]
